"""initial schema

Revision ID: 38b1cd7fe61c
Revises: 
Create Date: 2026-04-14 09:38:58.104095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b1cd7fe61c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('reasoning', 'language', 'knowledge', 'coding', 'safety', 'chat', 'instruction', 'custom', name='benchmarkcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_turns',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('parent_hash', sa.String(length=64), nullable=True),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('tail_hash', sa.String(length=64), nullable=False),
    sa.Column('caller_hash', sa.String(length=64), nullable=True),
    sa.Column('deployed_model_id', sa.String(length=36), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('run_name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('compacted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_turns_caller_hash'), ['caller_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_turns_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_turns_deployed_model_id'), ['deployed_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_turns_parent_hash'), ['parent_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_turns_state_hash'), ['state_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_chat_turns_tail_hash'), ['tail_hash'], unique=False)

    op.create_table('cloud_accounts',
    sa.Column('provider', sa.Enum('aws', 'gcp', 'azure', name='cloudprovider'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', name='cloudaccountstatus'), nullable=False),
    sa.Column('gpu_quota_used', sa.Integer(), nullable=False),
    sa.Column('gpu_quota_total', sa.Integer(), nullable=False),
    sa.Column('monthly_spend', sa.Float(), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compute_nodes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pool', sa.Enum('training', 'serving', 'system', name='computepool'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cordoned', 'error', name='computenodestatus'), nullable=False),
    sa.Column('gpu_type', sa.String(length=128), nullable=False),
    sa.Column('gpu_total', sa.Integer(), nullable=False),
    sa.Column('gpu_used', sa.Integer(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('cpu_used_percent', sa.Float(), nullable=False),
    sa.Column('memory_total', sa.String(length=32), nullable=False),
    sa.Column('memory_used', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compute_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('cooldown', sa.String(length=64), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', name='integrationstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metrics',
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('run_name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metrics_model'), ['model'], unique=False)
        batch_op.create_index('ix_model_metrics_model_created', ['model', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metrics_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metrics_run_name'), ['run_name'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='projectstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('dstack_project_name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dstack_project_name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_namespace'), ['namespace'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('jwt_secret', sa.String(length=256), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('hub_key', sa.String(length=128), nullable=False),
    sa.Column('hub_secret', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('default_project_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('agent_flows',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('single_agent', 'multi_agent', name='agentflowtype'), nullable=False),
    sa.Column('agents', sa.JSON(), nullable=True),
    sa.Column('max_rollout_tokens', sa.Integer(), nullable=False),
    sa.Column('steps_per_episode', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'error', name='agentflowstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_flows_project_id'), ['project_id'], unique=False)

    op.create_table('alerts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'warning', 'info', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('agent', 'model', 'compute', 'policy', name='alertsourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_project_id'), ['project_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('hashed_key', sa.String(length=512), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', name='apikeystatus'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_instances',
    sa.Column('provider', sa.Enum('aws', 'gcp', 'azure', name='cloudprovider'), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('instance_type', sa.String(length=64), nullable=False),
    sa.Column('gpu_type', sa.String(length=128), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'provisioning', 'terminated', name='cloudinstancestatus'), nullable=False),
    sa.Column('spot', sa.Boolean(), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=False),
    sa.Column('workload_id', sa.String(length=36), nullable=True),
    sa.Column('workload_type', sa.Enum('training', 'serving', 'eval', name='cloudworkloadtype'), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('auto_terminate_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cloud_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloud_instances_project_id'), ['project_id'], unique=False)

    op.create_table('datasets',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('format', sa.Enum('sft', 'dpo', 'grpo', 'rlhf', name='datasetformat'), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('ready', 'building', 'error', name='datasetstatus'), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('evaluators',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reward_type', sa.Enum('binary', 'continuous', name='rewardtype'), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'error', name='evaluatorstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluators_project_id'), ['project_id'], unique=False)

    op.create_table('local_tasks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('import_model', 'import_dataset', 'local_inference', 'local_training', name='localtasktype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='localtaskstatus'), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.String(length=255), nullable=True),
    sa.Column('log_path', sa.String(length=512), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('local_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_tasks_requested_by_id'), ['requested_by_id'], unique=False)

    op.create_table('managed_jobs',
    sa.Column('dstack_run_name', sa.String(length=100), nullable=True),
    sa.Column('dstack_project_name', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('workload_type', sa.Enum('training', 'serving', 'eval', name='cloudworkloadtype'), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('task_yaml', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accelerators', sa.String(length=128), nullable=True),
    sa.Column('cloud', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('use_spot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_jobs_dstack_run_name'), ['dstack_run_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_jobs_requested_by_id'), ['requested_by_id'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('transport', sa.Enum('sse', 'stdio', name='mcptransport'), nullable=False),
    sa.Column('auth', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', name='mcpstatus'), nullable=False),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('exposed_tools', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_project_id'), ['project_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event')
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='projectmemberrole'), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('added_by_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('rl_experiments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='experimentstatus'), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rl_experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rl_experiments_project_id'), ['project_id'], unique=False)

    op.create_table('serving_services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('dstack_run_name', sa.String(length=100), nullable=True),
    sa.Column('dstack_project_name', sa.String(length=50), nullable=True),
    sa.Column('task_yaml', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('accelerators', sa.String(length=128), nullable=True),
    sa.Column('infra', sa.String(length=128), nullable=True),
    sa.Column('instance_type', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('use_spot', sa.Boolean(), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('readiness_path', sa.String(length=255), nullable=True),
    sa.Column('load_balancing_policy', sa.String(length=64), nullable=True),
    sa.Column('update_mode', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('serving_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serving_services_dstack_run_name'), ['dstack_run_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_serving_services_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serving_services_requested_by_id'), ['requested_by_id'], unique=False)

    op.create_table('sft_experiments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='experimentstatus'), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sft_experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sft_experiments_project_id'), ['project_id'], unique=False)

    op.create_table('skills',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=False),
    sa.Column('compatibility', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('allowed_tools', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'error', name='skillstatus'), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_project_id'), ['project_id'], unique=False)

    op.create_table('tools',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('tool', 'rag', 'workflow', 'guardrail', 'output', name='toolcategory'), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'error', 'deploying', name='toolstatus'), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_project_id'), ['project_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('admin', 'skill_author', 'devops', 'developer', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('dataset_pipeline_steps',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('source', 'transform', 'output', name='pipelinesteptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'running', 'pending', name='pipelinestepstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_pipeline_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_pipeline_steps_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('deployed_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('base_model', sa.String(length=512), nullable=False),
    sa.Column('family', sa.String(length=128), nullable=True),
    sa.Column('param_count', sa.String(length=32), nullable=True),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('quantization', sa.String(length=64), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('namespace', sa.String(length=128), nullable=True),
    sa.Column('source', sa.Enum('local_hub', 'huggingface', 'openrouter', 'url', name='modelsource'), nullable=True),
    sa.Column('serving_config', sa.JSON(), nullable=True),
    sa.Column('generation_defaults', sa.JSON(), nullable=True),
    sa.Column('serving_service_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('deployed_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['deployed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['serving_service_id'], ['serving_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('deployed_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployed_models_deployed_by_id'), ['deployed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployed_models_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployed_models_serving_service_id'), ['serving_service_id'], unique=False)

    op.create_table('rl_runs',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('grpo', 'ppo', name='rlmethod'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'queued', 'failed', name='runstatus'), nullable=False),
    sa.Column('agent_flow_id', sa.String(length=36), nullable=False),
    sa.Column('evaluator_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('algorithm', sa.JSON(), nullable=True),
    sa.Column('workflow', sa.JSON(), nullable=True),
    sa.Column('lr', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('grad_accum', sa.Integer(), nullable=False),
    sa.Column('epochs', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('warmup_steps', sa.Integer(), nullable=False),
    sa.Column('weight_decay', sa.Float(), nullable=False),
    sa.Column('scheduler', sa.String(length=64), nullable=False),
    sa.Column('optimizer', sa.String(length=64), nullable=False),
    sa.Column('lora', sa.JSON(), nullable=True),
    sa.Column('episodes', sa.JSON(), nullable=True),
    sa.Column('avg_steps_per_episode', sa.Float(), nullable=False),
    sa.Column('best_loss', sa.Float(), nullable=True),
    sa.Column('loss_curve', sa.JSON(), nullable=True),
    sa.Column('reward_curve', sa.JSON(), nullable=True),
    sa.Column('kl_div_curve', sa.JSON(), nullable=True),
    sa.Column('policy_loss_curve', sa.JSON(), nullable=True),
    sa.Column('grad_norm_curve', sa.JSON(), nullable=True),
    sa.Column('lr_curve', sa.JSON(), nullable=True),
    sa.Column('eval_results', sa.JSON(), nullable=True),
    sa.Column('compute', sa.Enum('local', 'aws', 'gcp', name='computetarget'), nullable=False),
    sa.Column('gpu', sa.String(length=128), nullable=False),
    sa.Column('gpu_util', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_flow_id'], ['agent_flows.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluators.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['rl_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rl_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rl_runs_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('sft_runs',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('sft', 'dpo', name='sftmethod'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'queued', 'failed', name='runstatus'), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('lr', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('grad_accum', sa.Integer(), nullable=False),
    sa.Column('epochs', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('warmup_steps', sa.Integer(), nullable=False),
    sa.Column('weight_decay', sa.Float(), nullable=False),
    sa.Column('scheduler', sa.String(length=64), nullable=False),
    sa.Column('optimizer', sa.String(length=64), nullable=False),
    sa.Column('lora', sa.JSON(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('label_smoothing', sa.Float(), nullable=True),
    sa.Column('ref_model', sa.String(length=255), nullable=True),
    sa.Column('best_loss', sa.Float(), nullable=True),
    sa.Column('loss_curve', sa.JSON(), nullable=True),
    sa.Column('lr_curve', sa.JSON(), nullable=True),
    sa.Column('grad_norm_curve', sa.JSON(), nullable=True),
    sa.Column('eval_results', sa.JSON(), nullable=True),
    sa.Column('compute', sa.Enum('local', 'aws', 'gcp', name='computetarget'), nullable=False),
    sa.Column('gpu', sa.String(length=128), nullable=False),
    sa.Column('gpu_util', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['sft_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sft_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sft_runs_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('agents',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('harness', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('running', 'deploying', 'stopped', 'error', name='agentstatus'), nullable=False),
    sa.Column('replicas', sa.JSON(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('env_vars', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('hub_ref', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['deployed_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_project_id'), ['project_id'], unique=False)

    op.create_table('checkpoints',
    sa.Column('sft_run_id', sa.String(length=36), nullable=True),
    sa.Column('rl_run_id', sa.String(length=36), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('best', sa.Boolean(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rl_run_id'], ['rl_runs.id'], ),
    sa.ForeignKeyConstraint(['sft_run_id'], ['sft_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoints_rl_run_id'), ['rl_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkpoints_sft_run_id'), ['sft_run_id'], unique=False)

    op.create_table('eval_runs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('compare_model_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'queued', name='evalrunstatus'), nullable=False),
    sa.Column('compute', sa.String(length=64), nullable=False),
    sa.Column('gpu', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['compare_model_id'], ['deployed_models.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['deployed_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_runs_project_id'), ['project_id'], unique=False)

    op.create_table('agent_mcp_servers',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('mcp_server_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'mcp_server_id')
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('agent_versions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('git_hash', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('live', 'previous', 'failed', name='agentversionstatus'), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)

    op.create_table('conversations',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'escalated', name='conversationstatus'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=64), nullable=False),
    sa.Column('avg_latency', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('eval_results',
    sa.Column('eval_run_id', sa.String(length=36), nullable=False),
    sa.Column('benchmark_id', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('sample_results', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'pending', 'failed', name='evalresultstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_results_eval_run_id'), ['eval_run_id'], unique=False)

    op.create_table('eval_run_benchmarks',
    sa.Column('eval_run_id', sa.String(length=36), nullable=False),
    sa.Column('benchmark_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('eval_run_id', 'benchmark_id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('annotations',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('skill_gap', 'trajectory_correction', 'quality_issue', name='annotationtype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_message_id'), ['message_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', 'timeout', name='toolcallstatus'), nullable=False),
    sa.Column('latency', sa.Integer(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_message_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_message_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    op.drop_table('eval_run_benchmarks')
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_results_eval_run_id'))

    op.drop_table('eval_results')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_project_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_agent_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))

    op.drop_table('agent_versions')
    op.drop_table('agent_tools')
    op.drop_table('agent_skills')
    op.drop_table('agent_mcp_servers')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_project_id'))

    op.drop_table('eval_runs')
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoints_sft_run_id'))
        batch_op.drop_index(batch_op.f('ix_checkpoints_rl_run_id'))

    op.drop_table('checkpoints')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_project_id'))

    op.drop_table('agents')
    with op.batch_alter_table('sft_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sft_runs_experiment_id'))

    op.drop_table('sft_runs')
    with op.batch_alter_table('rl_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rl_runs_experiment_id'))

    op.drop_table('rl_runs')
    with op.batch_alter_table('deployed_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployed_models_serving_service_id'))
        batch_op.drop_index(batch_op.f('ix_deployed_models_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployed_models_deployed_by_id'))

    op.drop_table('deployed_models')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('dataset_pipeline_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_pipeline_steps_dataset_id'))

    op.drop_table('dataset_pipeline_steps')
    op.drop_table('user_roles')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_project_id'))

    op.drop_table('tools')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_project_id'))

    op.drop_table('skills')
    with op.batch_alter_table('sft_experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sft_experiments_project_id'))

    op.drop_table('sft_experiments')
    with op.batch_alter_table('serving_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serving_services_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_serving_services_project_id'))
        batch_op.drop_index(batch_op.f('ix_serving_services_dstack_run_name'))

    op.drop_table('serving_services')
    with op.batch_alter_table('rl_experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rl_experiments_project_id'))

    op.drop_table('rl_experiments')
    op.drop_table('project_members')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_project_id'))

    op.drop_table('mcp_servers')
    with op.batch_alter_table('managed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_jobs_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_managed_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_managed_jobs_dstack_run_name'))

    op.drop_table('managed_jobs')
    with op.batch_alter_table('local_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_tasks_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_local_tasks_project_id'))

    op.drop_table('local_tasks')
    with op.batch_alter_table('evaluators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluators_project_id'))

    op.drop_table('evaluators')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('cloud_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_instances_project_id'))

    op.drop_table('cloud_instances')
    op.drop_table('api_keys')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_project_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('agent_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_flows_project_id'))

    op.drop_table('agent_flows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_username'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_namespace'))

    op.drop_table('projects')
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metrics_run_name'))
        batch_op.drop_index(batch_op.f('ix_model_metrics_project_name'))
        batch_op.drop_index('ix_model_metrics_model_created')
        batch_op.drop_index(batch_op.f('ix_model_metrics_model'))
        batch_op.drop_index(batch_op.f('ix_model_metrics_created_at'))

    op.drop_table('model_metrics')
    op.drop_table('integrations')
    op.drop_table('compute_policies')
    op.drop_table('compute_nodes')
    op.drop_table('cloud_accounts')
    with op.batch_alter_table('chat_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_turns_tail_hash'))
        batch_op.drop_index(batch_op.f('ix_chat_turns_state_hash'))
        batch_op.drop_index(batch_op.f('ix_chat_turns_parent_hash'))
        batch_op.drop_index(batch_op.f('ix_chat_turns_deployed_model_id'))
        batch_op.drop_index(batch_op.f('ix_chat_turns_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_chat_turns_caller_hash'))

    op.drop_table('chat_turns')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
