model: Qwen/Qwen3-0.6B

# Quantization scheme: fp8 (W8A8), awq (INT4 W4A16), gptq_int4 (INT4 W4A16), qptq_int8 (INT8 W8A8), nvfp4 (NVidia FP4)
scheme: gptq_int4

# Maximum sequence length for calibration
max_seq_len: 2048

# exported_model
save_path: output/Qwen3-0.6B-FP8-Dynamic

sequence_len: 2048

# calibration datasets
datasets:
#  - path: "invergent/self-cognition"
#    split: "train"
#    samples: 128
#    type: instruction
#    instruction_field: question
#    output_field: answer

#  - path: "HuggingFaceH4/ultrachat_200k"
#    split: "train_sft"
#    samples: 128
#    type: conversation
#    messages_field: messages
#    message_property_mappings:
#      role: role
#      content: content
  - path: "invergent/densemax-self-cognition"
    type: conversation
    split: train
    samples: 128
    messages_field: messages
    message_property_mappings:
      role: role
      content: content
