model: Qwen/Qwen3-0.6B

# Quantization scheme: fp8 (W8A8), awq (INT4 W4A16), gptq_int4 (INT4 W4A16), qptq_int8 (INT8 W8A8), nvfp4 (NVidia FP4)
scheme: gptq_int4

# Maximum sequence length for calibration
max_seq_len: 2048

# exported_model
save_path: output/Qwen3-0.6B-FP8-Dynamic

# calibration datasets
datasets:
  - name: "allenai/c4"
    split: "train"
    subset: "yo"
    samples: 256
  - name: "HuggingFaceH4/ultrachat_200k"
    split: "train_sft"
    samples: 256

