#!/usr/bin/env python3
"""Generate the MoE Marlin instantiations surogate serve needs.

vLLM ships a generator that enumerates every quantisation family it supports; we
need one corner of it - bf16 activations, kU4B8 weights (our Q4G64 residency is
offset-8 4-bit, which is exactly that type), bf16 scales, group 64 - so this
emits only those instantiations and the selector that reaches them.

Run from the repo root:
    python3 csrc/src/serve/ops/sparse_moe/marlin/generate_moe_kernels.py
"""

from __future__ import annotations

import pathlib

HERE = pathlib.Path(__file__).resolve().parent

A_TYPE = "vllm::kBFloat16.id()"
B_TYPE = "vllm::kU4B8.id()"
C_TYPE = "vllm::kBFloat16.id()"
S_TYPE = "vllm::kBFloat16.id()"

# thread_k, thread_n, num_threads - vLLM's small- and large-batch tables, merged.
THREAD_CONFIGS = [(128, 128, 256), (64, 256, 256), (64, 128, 128), (128, 64, 128)]

# 0.5 means m_block_size_8: one 16-row block holding 8 rows.
THREAD_M_BLOCKS = [0.5, 1, 2, 3, 4]

# group_blocks = group_size / 16. Our routed experts are group 64 -> 4.
# -1 is the channelwise case, kept so the selector can answer for it.
GROUP_BLOCKS = [-1, 4]

STAGES = 4

HEAD = """// Generated by generate_moe_kernels.py from the vendored vLLM MoE Marlin
// template (Apache-2.0). Do not edit by hand.
// clang-format off

#include "ops/sparse_moe/marlin/vendor/kernel.h"
#include "ops/sparse_moe/marlin/vendor/marlin_moe_template.h"

namespace MARLIN_NAMESPACE_NAME {

"""

TAIL = """
} // namespace MARLIN_NAMESPACE_NAME
"""


def configurations():
    for thread_k, thread_n, threads in THREAD_CONFIGS:
        for m in THREAD_M_BLOCKS:
            for group_blocks in GROUP_BLOCKS:
                m_block_size_8 = m == 0.5
                thread_m_blocks = 1 if m_block_size_8 else int(m)
                # The template's k/n are in 16-wide blocks.
                yield {
                    "threads": threads,
                    "thread_m_blocks": thread_m_blocks,
                    "thread_n_blocks": thread_n // 16,
                    "thread_k_blocks": thread_k // 16,
                    "m_block_size_8": "true" if m_block_size_8 else "false",
                    "group_blocks": group_blocks,
                }


def instantiation(cfg) -> str:
    return (
        "template __global__ void Marlin<"
        f"{A_TYPE}, {B_TYPE}, {C_TYPE}, {S_TYPE}, "
        f"{cfg['threads']}, {cfg['thread_m_blocks']}, {cfg['thread_n_blocks']}, "
        f"{cfg['thread_k_blocks']}, {cfg['m_block_size_8']}, {STAGES}, "
        f"{cfg['group_blocks']}, false>( MARLIN_KERNEL_PARAMS );"
    )


def selector_arm(cfg) -> str:
    return (
        f"  if (threads == {cfg['threads']} && "
        f"thread_m_blocks == {cfg['thread_m_blocks']} && "
        f"thread_n_blocks == {cfg['thread_n_blocks']} && "
        f"thread_k_blocks == {cfg['thread_k_blocks']} && "
        f"m_block_size_8 == {cfg['m_block_size_8']} && "
        f"group_blocks == {cfg['group_blocks']}) {{\n"
        f"    return Marlin<{A_TYPE}, {B_TYPE}, {C_TYPE}, {S_TYPE}, "
        f"{cfg['threads']}, {cfg['thread_m_blocks']}, {cfg['thread_n_blocks']}, "
        f"{cfg['thread_k_blocks']}, {cfg['m_block_size_8']}, {STAGES}, "
        f"{cfg['group_blocks']}, false>;\n"
        f"  }}\n"
    )


def main() -> None:
    configs = list(configurations())
    kernels = HEAD + "\n".join(instantiation(c) for c in configs) + "\n" + TAIL
    (HERE / "marlin_moe_kernels_generated.cu").write_text(kernels)

    selector = (
        "// Generated by generate_moe_kernels.py. Do not edit by hand.\n"
        "// clang-format off\n"
        "// Included inside marlin_moe_select_kernel(), which owns the parameters.\n\n"
        + "".join(selector_arm(c) for c in configs)
    )
    (HERE / "marlin_moe_selector_generated.h").write_text(selector)
    print(f"generated {len(configs)} MoE Marlin kernels")


if __name__ == "__main__":
    main()
