# GRPO Orchestrator Example

model:
  # name: "./Qwen3-0.6B-NVFP4"
  name: "./reverse-fft-NVFP4"
  lora_adapter: "default"
  lora_rank: 16
  lora_alpha: 32

env:
  - id: reverse-text

batch_size: 128
rollouts_per_example: 16
seq_len: 2048
max_steps: 20

sampling:
  max_tokens: 128

  