model: openai/gpt-oss-20b
output_dir: ./output_gpt

per_device_train_batch_size: 1
gradient_accumulation_steps: 4

sample_packing: true
sequence_len: 512
gpus: 1

max_steps: 50

learning_rate: 2e-4

recipe: bf16
warmup_ratio: 0.1

lora: true
lora_rank: 16
lora_alpha: 32
lora_dtype: bf16
lora_dropout: 0

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_up_proj
  - down_proj

dataloader_num_workers: 4
datasets:
  - path: "OpenLLM-Ro/ro_gsm8k"
    type: auto
