model: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
output_dir: ./output_nemo

per_device_train_batch_size: 1
gradient_accumulation_steps: 4

sample_packing: true
sequence_len: 512

max_steps: 50
eval_steps: 10
save_steps: 0

learning_rate: 2e-4

recipe: bf16
lmhead_chunks: 8
warmup_ratio: 0.1

lora: true
lora_rank: 16
lora_alpha: 32
lora_dtype: bf16

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

qlora_bnb: true
qlora_offload_experts: true
zero_level: 2
offload_master: true
offload_grads: true
offload_optimizer: true
use_zero_copy: true

dataloader_num_workers: 4
datasets:
  - path: "OpenLLM-Ro/ro_gsm8k"
    type: auto
