model: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
model_type: qwen3_moe
output_dir: ./output_nemo
merge_adapter: false
apply_recommended_values: false

per_device_train_batch_size: 1
gradient_accumulation_steps: 1

sample_packing: true
sequence_len: 2048

num_epochs: 2
eval_steps: 25
save_steps: 0

learning_rate: 2e-4

recipe: bf16
lmhead_chunks: 8
warmup_steps: 20

lora: true
lora_rank: 16
lora_alpha: 32
lora_dtype: bf16

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

qlora_bnb: true
qlora_bnb_block_size: 64
qlora_bnb_double_quant: true
qlora_offload_experts: true
debug_memory_breakdown: true
offload_residual: true
offload_optimizer: true
use_cuda_graphs: false

dataloader_num_workers: 4
datasets:
  - path: "OpenLLM-Ro/ro_gsm8k"
    type: auto
