model: Qwen/Qwen3-4B
model_type: qwen3
save_path: ./output

apply_recommended_values: true

sample_packing: false
num_train_epochs: 15
sequence_len: 4096

learning_rate: 2e-4

qlora: true
lora_rank: 8
lora_alpha: 16
lora_target_modules:
  - all-linear

datasets:
  - path: "invergent/alpaca-gpt4-data-en"
    type: instruction
    instruction_field: instruction
    input_field: input
    output_field: output

