model: Qwen/Qwen3-0.6B
output_dir: ./output
merge_adapter: false
apply_recommended_values: false
gpus: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 2

use_cuda_graphs: false
sample_packing: true
sequence_len: 2048
loss_scale: default
max_steps: 3

learning_rate: 2e-4
recipe: bf16
recompute: true

lora: true
lora_rank: 16
lora_alpha: 32
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

validation_split_ratio: 0.05
eval_steps: 10
save_steps: 500
weight_decay: 0.0
dataloader_num_workers: 4
datasets:
  - path: "output_dataset_identity.jsonl"
    type: auto