model: ./output_moe
model_type: qwen3_moe
output_dir: ./output_moe_2
merge_adapter: false
apply_recommended_values: false

per_device_train_batch_size: 1
gradient_accumulation_steps: 4

sample_packing: true
sequence_len: 512

num_epochs: 2
eval_steps: 25
save_steps: 0

learning_rate: 2e-4

recipe: bf16
lmhead_chunks: 8
warmup_steps: 20
use_cuda_graphs: false
use_dsl_ir: true

lora: true
lora_rank: 16
lora_alpha: 32
lora_dtype: bf16

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

qlora_bnb: true

dataloader_num_workers: 4
datasets:
  - path: "OpenLLM-Ro/ro_gsm8k"
    type: auto
