model: Qwen/Qwen3-8B
output_dir: ./output

per_device_train_batch_size: 2
gradient_accumulation_steps: 4

sample_packing: true
sequence_len: 2048

num_epochs: 2
eval_steps: 25

learning_rate: 2e-4

recipe: bf16
debug_memory_breakdown: true
lora: true
lora_rank: 16
lora_alpha: 32
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

qlora_bnb: true
qlora_bnb_block_size: 64
qlora_bnb_double_quant: true

dataloader_num_workers: 4
datasets:
  - path: "OpenLLM-Ro/ro_gsm8k"
    type: auto
