model: Qwen/Qwen3-0.6B
model_type: qwen3_thinking

# Model configuration. Attention implementation. Options include 'sdpa', 'eager', 'flash_attention_2', 'flash_attention_3'
# Default is None, reading from config.json.
attn_impl: flash_attention_2

# Chat template configuration

# Default is None, which automatically selects the corresponding template for the given model.
template: None
# Custom system message field. Accepts either a string or a path to a .txt file. Default is None, using the default system message defined in the registered template.
system: None
# Maximum token length after tokenizer.encode for a single data sample (to prevent OOM during training).
# Samples exceeding this limit are handled according to truncation_strategy.
# Default is None, meaning it’s set to the model’s maximum supported sequence length (max_model_len).
max_length: None
# How to handle samples exceeding max_length.
# Options: 'delete', 'left', 'right', representing deletion, left-truncation, and right-truncation respectively.
# Default is 'delete'.
truncation_strategy: delete

# Training configuration

# Whether to enable the Liger kernel to accelerate training and reduce GPU memory consumption.
# Liger kernel does not support device_map. Use DDP or DeepSpeed for multi-GPU training.
# Defaults to False.
use_liger_kernel: False
# Whether to use gradient checkpointing. Default is True.
# This significantly reduces GPU memory usage but slows down training.
gradient_checkpointing: True
# Can be set to 'zero0', 'zero1', 'zero2', 'zero3', 'zero2_offload', 'zero3_offload' to use built-in DeepSpeed configurations.
# You can also pass a path to a custom DeepSpeed config file.
# Default is None
deepspeed: None
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
# Default is None, meaning gradient_accumulation_steps is automatically calculated so that total_batch_size >= 16
# total batch size is computed as per_device_train_batch_size * gradient_accumulation_steps * world_size.
# In GRPO training, default is 1.
gradient_accumulation_steps: None
# Weight decay coefficient. Default is 0.1.
weight_decay: 0.1
# Default is 1e-5 for full-parameter training, and 1e-4 for LoRA and other tuners.
learning_rate: 1e-4
# Type of learning rate scheduler. Default is 'cosine'.
lr_scheduler_type: cosine
# Possible values: 'tensorboard', 'wandb', 'swanlab'
# Default is 'tensorboard'
report_to: tensorboard
# logging_first_step: Whether to log metrics at the first step. Default is True.
logging_first_step: True
# Interval for logging. Default is 5.
logging_steps: 5
# Force training to stop after reaching max_epochs, then evaluate and save the model.
# Useful when using streaming datasets. Default is None.
max_epochs: None
# Number of training epochs. Default is 3.
num_train_epochs: 3
# Strategy for saving checkpoints. Options: 'no', 'steps', 'epoch'. Default is 'steps'.
save_strategy: steps
# Save checkpoint every X steps. Default is 500.
save_steps: 500
#  Maximum number of checkpoints to keep. Older checkpoints are deleted. Default is None (keep all).
save_total_limit: None
# Default is None, following save_strategy
# If neither val_dataset nor eval_dataset is used and split_dataset_ratio=0, defaults to 'no'
eval_strategy: None
# If evaluation dataset exists, follows save_steps.
eval_steps: None
# Maximum number of training steps. Must be set when using streaming datasets. Default is -1.
max_steps: -1
warmup_ratio: 0
# Save weights on every node. Default is False. Relevant in multi-node training.
# In multi-node training, output_dir is typically set to a shared directory, so this parameter usually doesn’t need to be set.
save_on_each_node: False
# Path to resume training from. Default is None.
# loads model weights, optimizer state, random seed, and resumes training from the last step.
resume_from_checkpoint: None
# Gradient clipping. Default is 1.
# The logged grad_norm reflects the value before clipping.
max_grad_norm: 1
# Optional values are "nccl", "gloo", "mpi", "ccl", "hccl", "cncl", "mccl". Default is None, which enables automatic selection.
ddp_backend: None

# Tuner configuration
seed: 42
tuner_backend: peft # 'peft', 'unsloth'
train_type: lora
lora_rank: 8
lora_alpha: 32
lora_dropout: 0.05
# Possible values are ‘none’, ‘all’. If you want to make all biases trainable, you can set it to 'all'
lora_bias: none
lora_dtype:
# Specifies which modules to apply LoRA to. Default is ['all-linear']. You can also specify suffixes of modules
# q_proj k_proj v_proj
target_modules: ['all-linear']

# Whether to use sequence packing to improve computational efficiency
# (better load balancing across nodes and processes, higher GPU utilization) and stabilize GPU memory usage. 
# Default is False. Currently supported in CPT/SFT/DPO/KTO/GKD.
# When using packing, please combine it with attn_impl: flash_attn
packing: False
 # the length to use for packing. Defaults to None, in which case it is set to max_length.
packing_length: None
# Number of processes for packing, default is 1.
# Note that different values of packing_num_proc will result in different packed datasets.
# (This parameter does not take effect during streaming packing)
packing_num_proc: 1

datasets:
  - path: "wikimedia/wikipedia"
    subset: '20231101.ab'
    split: "train"
    samples: 256
    type: text
    text_field: text