model: Qwen/Qwen3-8B-FP8
#model_type: qwen3
output_dir: ./output
merge_adapter: false
apply_recommended_values: false

per_device_train_batch_size: 2
gradient_accumulation_steps: 4
#deepspeed_level: zero2

sample_packing: true
sequence_len: 2048

num_epochs: 1

save_steps: 1000

learning_rate: 2e-4

lora_rank: 16
lora_alpha: 32
lora_target_modules:
  - all-linear

datasets:
  - path: "mlabonne/FineTome-100k"
    samples: 10000
    type: auto


