model: Qwen/Qwen3-30B-A3B
model_type: qwen3_moe
output_dir: ./output_moe

per_device_train_batch_size: 1
gradient_accumulation_steps: 4

sample_packing: true
sequence_len: 512
gpus: 4
ep_size: 4
ep_load_balance_threshold: 1.0

max_steps: 50
eval_steps: 0

learning_rate: 2e-4

recipe: fp8-hybrid
lmhead_chunks: 8
warmup_ratio: 0.1

lora: true
lora_rank: 16
lora_alpha: 32
lora_dtype: bf16

qlora_fp8: true
qlora_offload_experts: true
# qlora_selective_expert_dequant: true

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

dataloader_num_workers: 4
datasets:
  - path: "OpenLLM-Ro/ro_gsm8k"
    type: auto
