model: Qwen/Qwen3-0.6B
#model_type: qwen3
output_dir: ./output
merge_adapter: false
apply_recommended_values: false

per_device_train_batch_size: 2
gradient_accumulation_steps: 4

sample_packing: true
sequence_len: 2048

max_steps: 100
save_steps: 1000

learning_rate: 2e-4

recipe: fp8-hybrid
qlora_fp4: true
fp4_backend: cutlass

# Layers 0 and 1 (first 2) stay in BF16
# Layers N-8 through N-1 (last 8) stay in BF16
# All middle layers use FP4
skip_quant_first_layers: 2
skip_quant_last_layers: 8

lora: true
lora_rank: 16
lora_alpha: 32
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

dataloader_num_workers: 4
datasets:
  - path: "mlabonne/FineTome-100k"
    samples: 1000
    type: auto


